language: python
python:
    - 3.4
services:
    - redis-server
    - elasticsearch
addons:
    rethinkdb: '2.3.4'
before_install:
    - nvm install 6.7.0
install:
    - pip install -r server/requirements.txt
    - pip install pytest coverage flake8
    - ls ~/virtualenv/
    - source ~/virtualenv/python2.7/bin/activate
    - nvm use 6.7.0
    - 'cd client && npm install && cd ..'
    - source ~/virtualenv/python3.4/bin/activate
script:
    - flake8 server/**.py
    - coverage run --module py.test server
    - nvm use 6.7.0
    - 'cd client && npm test && cd ..'
after_success:
    - coverage report --omit="server/test/*,*site-packages*,*distutils*"
notifications:
    email: true
