sudo: required
language: python
python:
    - 3.4
services:
    - redis-server
    - elasticsearch
before_install:
    - nvm install 6.7.0
    - node --version
    - 'source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list'
    - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
    - sudo apt-get -y update
    - sudo apt-get -y install rethinkdb
    - rethinkdb --daemon
install:
    - pip install -r server/requirements.txt
    - pip install pytest coverage flake8
    - ls ~/virtualenv/
    - source ~/virtualenv/python2.7/bin/activate
    - nvm use 6.7.0
    - 'cd client && npm install && cd ..'
    - source ~/virtualenv/python3.4/bin/activate
script:
    - flake8 server/**.py
    - coverage run --module py.test server
    - nvm use 6.7.0
    - 'cd client && npm test && cd ..'
after_success:
    - coverage report --omit="server/test/*,*site-packages*,*distutils*"
notifications:
  email: true
