version: '3'
services:
  postgres:
    # https://hub.docker.com/_/postgres/
    image: 'postgres:9.6-alpine'
    ports:
     - '5432:5432'
    environment:
      POSTGRES_DB: sagefy
      POSTGRES_USER: sagefy
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
  postgres-test:
    # https://hub.docker.com/_/postgres/
    image: 'postgres:9.6-alpine'
    ports:
     - '5433:5432'
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
    volumes:
     - ./postgres-test-data:/var/lib/postgresql/data
  redis:
    # https://hub.docker.com/_/redis/
    image: 'redis:3.2-alpine'
    ports:
     - "6379:6379"
  elasticsearch:
    # https://hub.docker.com/_/elasticsearch/
    image: 'elasticsearch:5.5-alpine'
    ports:
     - '9200:9200'
    volumes:
     - ./elasticsearch-data:/usr/share/elasticsearch/data
  server:
    # https://hub.docker.com/_/python/
    build: ./server
    ports:
     - "8653:8653"
    volumes:
     - ./server:/www
     - ./content:/content
  client:
    # https://hub.docker.com/_/node/
    build: ./client
    ports:
     - "5984:5984"
    volumes:
     - ./client:/www
     - ./content:/content
    links:
     - server
  nginx:
    # https://hub.docker.com/_/nginx/
    image: 'nginx:1.13-alpine'
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/statics:/var/www
    ports:
     - "80:80"
    links:
     - server
     - client
