version: '3'
services:
  nginx:
    # https://hub.docker.com/_/nginx/
    image: 'nginx:1.15-alpine'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/statics:/var/www
    ports:
      - '80:80'
    links:
      - client
  client:
    # https://hub.docker.com/_/node/
    build: ./client
    ports:
      - '5984:5984'
    volumes:
      - ./client:/client
