version: '3'
services:
  nginx:
    # https://hub.docker.com/_/nginx/
    image: 'nginx:1.15-alpine'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/nginx
    ports:
      - '80:80'
    links:
      - client
      - server
  client:
    # https://hub.docker.com/_/node/
    build: ./client
    ports:
      - '2602:2602'
    volumes:
      - ./client:/client
    links:
      - server
    env_file:
      - .env
  server:
    # https://hub.docker.com/_/node/
    build: ./server
    ports:
      - '2601:2601'
    volumes:
      - ./server:/server
    links:
      - postgres
    env_file:
      - .env
  postgres:
    # https://hub.docker.com/_/postgres/
    build: ./postgres
    ports:
      - '2600:2600'
    environment:
      POSTGRES_DB: sagefy
      POSTGRES_USER: sagefy
    command: -p 2600
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres:/postgres
    env_file:
      - .env
