version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
      - image: heiskr/circleci-postgres-alpine-json-schema
        environment:
          POSTGRES_USER: sagefy
          POSTGRES_DB: sagefy
        command: -p 2600
    steps:
      - checkout
      - run:
          name: Run migrations
          command: |
            curl -fsSL -o dbmate https://github.com/amacneil/dbmate/releases/download/v1.4.1/dbmate-linux-amd64
            chmod +x dbmate
            ./dbmate wait && ./dbmate -d "./postgres/migrations" -s "./postgres/schema.sql" up
          environment:
            DATABASE_URL: postgres://sagefy@localhost:2600/sagefy?sslmode=disable
      - run: npm install
      - run: npm test
