version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: sagefy
          POSTGRES_DB: sagefy
    steps:
      - checkout
      - run: npm install
      - run: '(cd client && npm install)'
      - run: '(cd server && npm install)'
      - run: npm test
